server:
  port: 8086
spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: 10.5.2.242
    port: 5672
    username: rabbitmq
    password: rabbitmq
endpoints:
#actuator的metrics接口是否需要安全保证
  metrics:
    sensitive: false
    enabled: true
#actuator的health接口是否需要安全保证
  health:
    enabled: true
    sensitive: false

